name: PHPUnit

on: [ push, pull_request ]

env:
  SWOOLE_VERSION: '5.1.1'
  SWOW_VERSION: 'v1.2.0'

jobs:
  ci:
    name: Test PHP ${{ matrix.php-version }} on ${{ matrix.engine }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '8.1', '8.2', '8.3' ]
        engine: [ 'none' ]
      max-parallel: 9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
      - name: Setup Packages
        run: composer update -o --no-scripts
      - name: Setup MySQL Server
        run: |
          docker run --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true -d mysql:8.0 --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
          sleep 30
          mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS test charset=utf8mb4 collate=utf8mb4_unicode_ci;"
      - name: Run Test Cases
        run: |
          vendor/bin/php-cs-fixer fix --dry-run
          composer analyse
          composer test
